blocks:
  1:
    world: "game"
    x: 167.0
    y: 126.0
    z: 5.0
  2:
    world: "game"
    x: 151.0
    y: 114.0
    z: 9.0
  3:
    world: "game"
    x: 187.0
    y: 104.0
    z: 3.0
  4:
    world: "game"
    x: 192.0
    y: 104.0
    z: 16.0
  5:
    world: "game"
    x: 194.0
    y: 103.0
    z: 12.0
  6:
    world: "game"
    x: 193.0
    y: 104.0
    z: 13.0
  7:
    world: "game"
    x: 196.0
    y: 103.0
    z: 4.0
  8:
    world: "game"
    x: 172.0
    y: 97.0
    z: 2.0
  9:
    world: "game"
    x: 149.0
    y: 99.0
    z: 1.0
  10:
    world: "game"
    x: 167.0
    y: 98.0
    z: 10.0
  11:
    world: "game"
    x: 168.0
    y: 97.0
    z: 9.0
  12:
    world: "game"
    x: 182.0
    y: 103.0
    z: -8.0
  13:
    world: "game"
    x: 124.0
    y: 105.0
    z: 12.0