gameLocation:
  world: game
  x: 0.0
  y: 65.0
  z: 0.0

lobbyLocation:
  world: world
  x: 50.0
  y: 65.0
  z: 50.0

meetingStartLocation:
  world: game
  x: 203.0
  y: 110.0
  z: 4.0

meetingEndLocation:
  world: game
  x: 203.0
  y: 110.0
  z: 12.0

bossBarNameDay: "Иконка солнца"
bossBarNameNight: "Иконка ночи"
nightDuration: 4800
dayDuration: 12000
sabotageDuration: 6000

votingTitleMain: "ГОЛОСОВАНИЕ"
votingTitleSub: "Выберите кого вы хотите изгнать"
votingItemName: "Голосование"

nightTitleMain: "Ночь наступила!"
dayTitleMain: "День наступил!"

blockRepairActionBar: "Блок восстановлен, осталось: "

sabotageStartMessage: "Саботаж начался"
sabotageSuccessMessage: "САБОТАЖ УСПЕШНО УСТРАНЁН"
sabotageFailedMessage: "Саботаж не устранён, игра окончена"

votingSkippedMessage: "Голосование пропущено"
votingNoResultMessage: "Голосование не дало результата"
votingExileMessage: "Игрок изгнан"

blocksToBreak: 5
