name: MafiaGame
main: com.mirage.mafiagame.Plugin
version: 1.0
api-version: 1.16

commands:
  mafia:
    description: Mafia command
    usage: /<command>
    aliases: [maf]
  sudo:
    description: Sudo command
    usage: /<command> <player> <command>
    aliases: [su, s]
  test:
    description: Test command
    usage: /<command>
    aliases: [t]

depend:
  - packetevents
  - MineLib