name: MafiaGame
main: com.mirage.mafiagame.Plugin
version: 1.0
api-version: 1.16
commands:
  locations:
    description: Location commands
    usage: /<command>
    aliases: [loc]
libraries:
  - com.mirage:utils:1.0
  - com.mirage:packetapi:1.0
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.0.0
depend:
  - packetevents